name: gen_lang_example
description: Demonstrates how to use the gen_lang plugin.
publish_to: "none"

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  gen_lang:
    path: ../
flutter:
  uses-material-design: true
