name: gen_lang
description: >-
  gen_lang is a dart library for internationalization. Extracts messages
  to generate dart files required by Intl
version: 0.1.4
homepage: https://github.com/KingWu/gen_lang

environment:
  sdk: ">=2.19.4 <=3.0.0"

dependencies:
  args: ">=2.0.0 <3.0.0"
  path: ">=1.0.0 <2.0.0"
  ansicolor: ^2.0.1
  recase: ^4.1.0
